run:
  go: 1.21
  timeout: 5m
linters:
  enable:
    - dupl
    - dupword
    - forbidigo
    - gocritic
    - gofumpt
    - goimports
    - misspell
    - prealloc
    - revive
    - revive
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
linter-settings:
  forbidigo:
    forbid:
      - 'ioutil\.*'
issues:
  exclude-rules:
    - path: 'distribution\.go'
      linters:
        - dupl