Output scrabbler.gif

Set FontSize 34
Set Width 1800
Set Height 1000
Set Padding 40
Set Framerate 30
Set CursorBlink false
Set PlaybackSpeed 0.5

Set Theme { "name": "Challenger Deep", "background": "#1b182c" }

Hide
Type "go build -o scrabbler"
Enter
Type "./scrabbler"
Enter
Sleep 4

Show
Sleep 2
Type "?"
Sleep 2
Type "?"
Sleep 2
Right
Sleep 2
Enter@2 2
Sleep 2
Left
Sleep 2
Enter
Sleep 2
Ctrl+G
Sleep 2
Ctrl+G
Sleep 4

Hide
Ctrl+C
Type "rm -f scrabbler"
Enter