name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
          cache: false
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run tests
        run: go test -v -race ./...